export const REGISTER_SUBMIT = "REGISTER:SUBMIT";

export const REGISTER_SUCCESS = "REGISTER:SUCCESS";
export const REGISTER_FAILURE = "REGISTER:FAILURE";
export const REGISTER_REQUEST = "REGISTER:REQUEST";


export const DATA_UPDATE = "DATA_UPDATE:UPDATE";