export const REGISTER_SUBMIT = "REGISTER:SUBMIT";

export const LOGIN_SUCCESS = "REGISTER:SUCCESS";
export const LOGIN_FAILURE = "REGISTER:FAILURE";
export const LOGIN_REQUEST = "REGISTER:REQUEST";


export const DATA_UPDATE = "DATA_UPDATE:UPDATE";